### ISSUE TITLE
Travis builds can be faster

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/jhash#16]
Skip the install step like so:
```yaml
before_install:
 - chmod +x gradlew

install: echo "skipping install step"

script:
 - "./gradlew check"
```

The default install step runs gradle assemble. So doing that AND gradle check isn't really useful when tasks are being repeated on every build.
